repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.253'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.0.1'
    hooks:
    -   id: mypy
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        stages: [commit]